version: "3.5"

services:
  dynamo-db:
    container_name: trello-db
    image: amazon/dynamodb-local
    networks:
      - trello
    ports:
      - "8000:8000"

networks:
  trello:
    name: "trello-network"

volumes:
  db:
    driver: local
