Transform: AWS::Serverless-2016-10-31
Parameters:
  DiscordBotToken:
    Type: String
    Default: '{{resolve:secretsmanager:discord_interaction-secrets:SecretString:discord_interaction-bot-token}}'
    Description: Discord Bot Token for Trello to make return requests
  DiscordPublicKey:
    Type: String
    Default: '{{resolve:secretsmanager:discord_interaction-secrets:SecretString:discord_interaction-public-key}}'
    Description: Public Key of the Trello-Discord Application which is required to authenticate Discord Interactions
  TrelloApiKey:
    Type: String
    Default: '{{resolve:secretsmanager:discord_interaction-secrets:SecretString:trello-api-key}}'
    Description: Used as part of the OAuth flow to obtain user tokens.
  TrelloSecretKey:
    Type: String
    Default: '{{resolve:secretsmanager:discord_interaction-secrets:SecretString:trello-secret-key}}'
    Description: Used as part of the OAuth flow to obtain user tokens.
Resources:
  DiscordInteractionEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./discord_interaction
      Environment:
        Variables:
          DISCORD_PUBLIC_KEY: !Ref DiscordPublicKey
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Method: POST
            Path: "/discord_interaction"
      Handler: lambda_handler.handler
      PackageType: Zip
      Runtime: python3.9
  GuildTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: guild_id
        Type: Number
      TableName: dti_guilds
  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: discord_id
        Type: Number
      TableName: dti_users